/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.f1x.api.message.fields;

// Generated by org.f1x.tools.DictionaryGenerator from QuickFIX dictionary
public enum AcctIDSource implements org.f1x.api.message.types.IntEnum {
	BIC(1),
	SID_CODE(2),
	TFM(3),
	OMGEO(4),
	DTCC_CODE(5),
	OTHER(99);

	private final int code;

	AcctIDSource (int code) {
		this.code  = code;
	}

	public int getCode() { return code; }

	public static AcctIDSource parse(String s) {
		switch(s) {
			case "1" : return BIC;
			case "2" : return SID_CODE;
			case "3" : return TFM;
			case "4" : return OMGEO;
			case "5" : return DTCC_CODE;
			case "99" : return OTHER;
		}
		return null;
	}

}