/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.f1x.api.message.fields;

// Generated by org.f1x.tools.DictionaryGenerator from QuickFIX dictionary
public enum AllocCancReplaceReason implements org.f1x.api.message.types.ByteEnum {
	ORIGINAL_DETAILS_INCOMPLETE_INCORRECT((byte)'1'),
	CHANGE_IN_UNDERLYING_ORDER_DETAILS((byte)'2');

	private final byte code;

	AllocCancReplaceReason (byte code) {
		this.code  = code;
	}

	public byte getCode() { return code; }

	public static AllocCancReplaceReason parse(String s) {
		switch(s) {
			case "1" : return ORIGINAL_DETAILS_INCOMPLETE_INCORRECT;
			case "2" : return CHANGE_IN_UNDERLYING_ORDER_DETAILS;
		}
		return null;
	}

}