/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.f1x.api.message.fields;

// Generated by org.f1x.tools.DictionaryGenerator from QuickFIX dictionary
public enum AllocIntermedReqType implements org.f1x.api.message.types.ByteEnum {
	PENDING_ACCEPT((byte)'1'),
	PENDING_RELEASE((byte)'2'),
	PENDING_REVERSAL((byte)'3'),
	ACCEPT((byte)'4'),
	BLOCK_LEVEL_REJECT((byte)'5'),
	ACCOUNT_LEVEL_REJECT((byte)'6');

	private final byte code;

	AllocIntermedReqType (byte code) {
		this.code  = code;
	}

	public byte getCode() { return code; }

	public static AllocIntermedReqType parse(String s) {
		switch(s) {
			case "1" : return PENDING_ACCEPT;
			case "2" : return PENDING_RELEASE;
			case "3" : return PENDING_REVERSAL;
			case "4" : return ACCEPT;
			case "5" : return BLOCK_LEVEL_REJECT;
			case "6" : return ACCOUNT_LEVEL_REJECT;
		}
		return null;
	}

}