/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.f1x.api.message.fields;

// Generated by org.f1x.tools.DictionaryGenerator from QuickFIX dictionary
public enum ApplQueueResolution implements org.f1x.api.message.types.ByteEnum {
	NO_ACTION_TAKEN((byte)'0'),
	QUEUE_FLUSHED((byte)'1'),
	OVERLAY_LAST((byte)'2'),
	END_SESSION((byte)'3');

	private final byte code;

	ApplQueueResolution (byte code) {
		this.code  = code;
	}

	public byte getCode() { return code; }

	public static ApplQueueResolution parse(String s) {
		switch(s) {
			case "0" : return NO_ACTION_TAKEN;
			case "1" : return QUEUE_FLUSHED;
			case "2" : return OVERLAY_LAST;
			case "3" : return END_SESSION;
		}
		return null;
	}

}