/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.f1x.api.message.fields;

// Generated by org.f1x.tools.DictionaryGenerator from QuickFIX dictionary
public enum BookingType implements org.f1x.api.message.types.ByteEnum {
	REGULAR_BOOKING((byte)'0'),
	CFD((byte)'1'),
	TOTAL_RETURN_SWAP((byte)'2');

	private final byte code;

	BookingType (byte code) {
		this.code  = code;
	}

	public byte getCode() { return code; }

	public static BookingType parse(String s) {
		switch(s) {
			case "0" : return REGULAR_BOOKING;
			case "1" : return CFD;
			case "2" : return TOTAL_RETURN_SWAP;
		}
		return null;
	}

}