/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.f1x.api.message.fields;

// Generated by org.f1x.tools.DictionaryGenerator from QuickFIX dictionary
public enum BusinessRejectReason implements org.f1x.api.message.types.ByteEnum {
	OTHER((byte)'0'),
	UNKOWN_ID((byte)'1'),
	UNKNOWN_SECURITY((byte)'2'),
	UNSUPPORTED_MESSAGE_TYPE((byte)'3'),
	APPLICATION_NOT_AVAILABLE((byte)'4'),
	CONDITIONALLY_REQUIRED_FIELD_MISSING((byte)'5'),
	NOT_AUTHORIZED((byte)'6'),
	DELIVERTO_FIRM_NOT_AVAILABLE_AT_THIS_TIME((byte)'7');

	private final byte code;

	BusinessRejectReason (byte code) {
		this.code  = code;
	}

	public byte getCode() { return code; }

	public static BusinessRejectReason parse(String s) {
		switch(s) {
			case "0" : return OTHER;
			case "1" : return UNKOWN_ID;
			case "2" : return UNKNOWN_SECURITY;
			case "3" : return UNSUPPORTED_MESSAGE_TYPE;
			case "4" : return APPLICATION_NOT_AVAILABLE;
			case "5" : return CONDITIONALLY_REQUIRED_FIELD_MISSING;
			case "6" : return NOT_AUTHORIZED;
			case "7" : return DELIVERTO_FIRM_NOT_AVAILABLE_AT_THIS_TIME;
		}
		return null;
	}

}