/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.f1x.api.message.fields;

// Generated by org.f1x.tools.DictionaryGenerator from QuickFIX dictionary
public enum CollStatus implements org.f1x.api.message.types.ByteEnum {
	UNASSIGNED((byte)'0'),
	PARTIALLY_ASSIGNED((byte)'1'),
	ASSIGNMENT_PROPOSED((byte)'2'),
	ASSIGNED((byte)'3'),
	CHALLENGED((byte)'4');

	private final byte code;

	CollStatus (byte code) {
		this.code  = code;
	}

	public byte getCode() { return code; }

	public static CollStatus parse(String s) {
		switch(s) {
			case "0" : return UNASSIGNED;
			case "1" : return PARTIALLY_ASSIGNED;
			case "2" : return ASSIGNMENT_PROPOSED;
			case "3" : return ASSIGNED;
			case "4" : return CHALLENGED;
		}
		return null;
	}

}