/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.f1x.api.message.fields;

// Generated by org.f1x.tools.DictionaryGenerator from QuickFIX dictionary
public enum CollAsgnReason implements org.f1x.api.message.types.ByteEnum {
	INITIAL((byte)'0'),
	SCHEDULED((byte)'1'),
	TIME_WARNING((byte)'2'),
	MARGIN_DEFICIENCY((byte)'3'),
	MARGIN_EXCESS((byte)'4'),
	FORWARD_COLLATERAL_DEMAND((byte)'5'),
	EVENT_OF_DEFAULT((byte)'6'),
	ADVERSE_TAX_EVENT((byte)'7');

	private final byte code;

	CollAsgnReason (byte code) {
		this.code  = code;
	}

	public byte getCode() { return code; }

	public static CollAsgnReason parse(String s) {
		switch(s) {
			case "0" : return INITIAL;
			case "1" : return SCHEDULED;
			case "2" : return TIME_WARNING;
			case "3" : return MARGIN_DEFICIENCY;
			case "4" : return MARGIN_EXCESS;
			case "5" : return FORWARD_COLLATERAL_DEMAND;
			case "6" : return EVENT_OF_DEFAULT;
			case "7" : return ADVERSE_TAX_EVENT;
		}
		return null;
	}

}