/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.f1x.api.message.fields;

// Generated by org.f1x.tools.DictionaryGenerator from QuickFIX dictionary
public enum CommType implements org.f1x.api.message.types.ByteEnum {
	PER_UNIT((byte)'1'),
	PERCENTAGE((byte)'2'),
	ABSOLUTE((byte)'3'),
	PERCENTAGE_WAIVED_CASH_DISCOUNT((byte)'4'),
	PERCENTAGE_WAIVED_ENHANCED_UNITS((byte)'5'),
	POINTS_PER_BOND_OR_OR_CONTRACT((byte)'6');

	private final byte code;

	CommType (byte code) {
		this.code  = code;
	}

	public byte getCode() { return code; }

	public static CommType parse(String s) {
		switch(s) {
			case "1" : return PER_UNIT;
			case "2" : return PERCENTAGE;
			case "3" : return ABSOLUTE;
			case "4" : return PERCENTAGE_WAIVED_CASH_DISCOUNT;
			case "5" : return PERCENTAGE_WAIVED_ENHANCED_UNITS;
			case "6" : return POINTS_PER_BOND_OR_OR_CONTRACT;
		}
		return null;
	}

}