/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.f1x.api.message.fields;

// Generated by org.f1x.tools.DictionaryGenerator from QuickFIX dictionary
public enum ConfirmStatus implements org.f1x.api.message.types.ByteEnum {
	RECEIVED((byte)'1'),
	MISMATCHED_ACCOUNT((byte)'2'),
	MISSING_SETTLEMENT_INSTRUCTIONS((byte)'3'),
	CONFIRMED((byte)'4'),
	REQUEST_REJECTED((byte)'5');

	private final byte code;

	ConfirmStatus (byte code) {
		this.code  = code;
	}

	public byte getCode() { return code; }

	public static ConfirmStatus parse(String s) {
		switch(s) {
			case "1" : return RECEIVED;
			case "2" : return MISMATCHED_ACCOUNT;
			case "3" : return MISSING_SETTLEMENT_INSTRUCTIONS;
			case "4" : return CONFIRMED;
			case "5" : return REQUEST_REJECTED;
		}
		return null;
	}

}