/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.f1x.api.message.fields;

// Generated by org.f1x.tools.DictionaryGenerator from QuickFIX dictionary
public enum ConfirmRejReason implements org.f1x.api.message.types.IntEnum {
	MISMATCHED_ACCOUNT(1),
	MISSING_SETTLEMENT_INSTRUCTIONS(2),
	OTHER(99);

	private final int code;

	ConfirmRejReason (int code) {
		this.code  = code;
	}

	public int getCode() { return code; }

	public static ConfirmRejReason parse(String s) {
		switch(s) {
			case "1" : return MISMATCHED_ACCOUNT;
			case "2" : return MISSING_SETTLEMENT_INSTRUCTIONS;
			case "99" : return OTHER;
		}
		return null;
	}

}