/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.f1x.api.message.fields;

// Generated by org.f1x.tools.DictionaryGenerator from QuickFIX dictionary
public enum ContAmtType implements org.f1x.api.message.types.ByteEnum {
	COMMISSION_AMOUNT((byte)'1'),
	COMMISSION_PERCENT((byte)'2'),
	INITIAL_CHARGE_AMOUNT((byte)'3'),
	INITIAL_CHARGE_PERCENT((byte)'4'),
	DISCOUNT_AMOUNT((byte)'5'),
	DISCOUNT_PERCENT((byte)'6'),
	DILUTION_LEVY_AMOUNT((byte)'7'),
	DILUTION_LEVY_PERCENT((byte)'8'),
	EXIT_CHARGE_AMOUNT((byte)'9');

	private final byte code;

	ContAmtType (byte code) {
		this.code  = code;
	}

	public byte getCode() { return code; }

	public static ContAmtType parse(String s) {
		switch(s) {
			case "1" : return COMMISSION_AMOUNT;
			case "2" : return COMMISSION_PERCENT;
			case "3" : return INITIAL_CHARGE_AMOUNT;
			case "4" : return INITIAL_CHARGE_PERCENT;
			case "5" : return DISCOUNT_AMOUNT;
			case "6" : return DISCOUNT_PERCENT;
			case "7" : return DILUTION_LEVY_AMOUNT;
			case "8" : return DILUTION_LEVY_PERCENT;
			case "9" : return EXIT_CHARGE_AMOUNT;
		}
		return null;
	}

}