/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.f1x.api.message.fields;

// Generated by org.f1x.tools.DictionaryGenerator from QuickFIX dictionary
public enum CrossType implements org.f1x.api.message.types.ByteEnum {
	CROSS_TRADE_WHICH_IS_EXECUTED_COMPLETELY_OR_NOT((byte)'1'),
	CROSS_TRADE_WHICH_IS_EXECUTED_PARTIALLY_AND_THE_REST_IS_CANCELLED((byte)'2'),
	CROSS_TRADE_WHICH_IS_PARTIALLY_EXECUTED_WITH_THE_UNFILLED_PORTIONS_REMAINING_ACTIVE((byte)'3'),
	CROSS_TRADE_IS_EXECUTED_WITH_EXISTING_ORDERS_WITH_THE_SAME_PRICE((byte)'4');

	private final byte code;

	CrossType (byte code) {
		this.code  = code;
	}

	public byte getCode() { return code; }

	public static CrossType parse(String s) {
		switch(s) {
			case "1" : return CROSS_TRADE_WHICH_IS_EXECUTED_COMPLETELY_OR_NOT;
			case "2" : return CROSS_TRADE_WHICH_IS_EXECUTED_PARTIALLY_AND_THE_REST_IS_CANCELLED;
			case "3" : return CROSS_TRADE_WHICH_IS_PARTIALLY_EXECUTED_WITH_THE_UNFILLED_PORTIONS_REMAINING_ACTIVE;
			case "4" : return CROSS_TRADE_IS_EXECUTED_WITH_EXISTING_ORDERS_WITH_THE_SAME_PRICE;
		}
		return null;
	}

}