/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.f1x.api.message.fields;

// Generated by org.f1x.tools.DictionaryGenerator from QuickFIX dictionary
public enum CustOrderCapacity implements org.f1x.api.message.types.ByteEnum {
	MEMBER_TRADING_FOR_THEIR_OWN_ACCOUNT((byte)'1'),
	CLEARING_FIRM_TRADING_FOR_ITS_PROPRIETARY_ACCOUNT((byte)'2'),
	MEMBER_TRADING_FOR_ANOTHER_MEMBER((byte)'3'),
	ALL_OTHER((byte)'4');

	private final byte code;

	CustOrderCapacity (byte code) {
		this.code  = code;
	}

	public byte getCode() { return code; }

	public static CustOrderCapacity parse(String s) {
		switch(s) {
			case "1" : return MEMBER_TRADING_FOR_THEIR_OWN_ACCOUNT;
			case "2" : return CLEARING_FIRM_TRADING_FOR_ITS_PROPRIETARY_ACCOUNT;
			case "3" : return MEMBER_TRADING_FOR_ANOTHER_MEMBER;
			case "4" : return ALL_OTHER;
		}
		return null;
	}

}