/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.f1x.api.message.fields;

// Generated by org.f1x.tools.DictionaryGenerator from QuickFIX dictionary
public enum HaltReason implements org.f1x.api.message.types.ByteEnum {
	ORDER_IMBALANCE((byte)'I'),
	EQUIPMENT_CHANGEOVER((byte)'X'),
	NEWS_PENDING((byte)'P'),
	NEWS_DISSEMINATION((byte)'D'),
	ORDER_INFLUX((byte)'E'),
	ADDITIONAL_INFORMATION((byte)'M');

	private final byte code;

	HaltReason (byte code) {
		this.code  = code;
	}

	public byte getCode() { return code; }

	public static HaltReason parse(String s) {
		switch(s) {
			case "I" : return ORDER_IMBALANCE;
			case "X" : return EQUIPMENT_CHANGEOVER;
			case "P" : return NEWS_PENDING;
			case "D" : return NEWS_DISSEMINATION;
			case "E" : return ORDER_INFLUX;
			case "M" : return ADDITIONAL_INFORMATION;
		}
		return null;
	}

}