/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.f1x.api.message.fields;

// Generated by org.f1x.tools.DictionaryGenerator from QuickFIX dictionary
public enum HandlInst implements org.f1x.api.message.types.ByteEnum {
	AUTOMATED_EXECUTION_ORDER_PRIVATE((byte)'1'),
	AUTOMATED_EXECUTION_ORDER_PUBLIC((byte)'2'),
	MANUAL_ORDER((byte)'3');

	private final byte code;

	HandlInst (byte code) {
		this.code  = code;
	}

	public byte getCode() { return code; }

	public static HandlInst parse(String s) {
		switch(s) {
			case "1" : return AUTOMATED_EXECUTION_ORDER_PRIVATE;
			case "2" : return AUTOMATED_EXECUTION_ORDER_PUBLIC;
			case "3" : return MANUAL_ORDER;
		}
		return null;
	}

}