/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.f1x.api.message.fields;

// Generated by org.f1x.tools.DictionaryGenerator from QuickFIX dictionary
public enum IOIQltyInd implements org.f1x.api.message.types.ByteEnum {
	LOW((byte)'L'),
	MEDIUM((byte)'M'),
	HIGH((byte)'H');

	private final byte code;

	IOIQltyInd (byte code) {
		this.code  = code;
	}

	public byte getCode() { return code; }

	public static IOIQltyInd parse(String s) {
		switch(s) {
			case "L" : return LOW;
			case "M" : return MEDIUM;
			case "H" : return HIGH;
		}
		return null;
	}

}