/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.f1x.api.message.fields;

// Generated by org.f1x.tools.DictionaryGenerator from QuickFIX dictionary
public enum ListExecInstType implements org.f1x.api.message.types.ByteEnum {
	IMMEDIATE((byte)'1'),
	WAIT_FOR_EXECUTE_INSTRUCTION((byte)'2'),
	EXCHANGE_SWITCH_CIV_ORDER_SELL_DRIVEN((byte)'3'),
	EXCHANGE_SWITCH_CIV_ORDER_BUY_DRIVEN_CASH_TOP_UP((byte)'4'),
	EXCHANGE_SWITCH_CIV_ORDER_BUY_DRIVEN_CASH_WITHDRAW((byte)'5');

	private final byte code;

	ListExecInstType (byte code) {
		this.code  = code;
	}

	public byte getCode() { return code; }

	public static ListExecInstType parse(String s) {
		switch(s) {
			case "1" : return IMMEDIATE;
			case "2" : return WAIT_FOR_EXECUTE_INSTRUCTION;
			case "3" : return EXCHANGE_SWITCH_CIV_ORDER_SELL_DRIVEN;
			case "4" : return EXCHANGE_SWITCH_CIV_ORDER_BUY_DRIVEN_CASH_TOP_UP;
			case "5" : return EXCHANGE_SWITCH_CIV_ORDER_BUY_DRIVEN_CASH_WITHDRAW;
		}
		return null;
	}

}