/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.f1x.api.message.fields;

// Generated by org.f1x.tools.DictionaryGenerator from QuickFIX dictionary
public enum ListStatusType implements org.f1x.api.message.types.ByteEnum {
	ACK((byte)'1'),
	RESPONSE((byte)'2'),
	TIMED((byte)'3'),
	EXECSTARTED((byte)'4'),
	ALLDONE((byte)'5'),
	ALERT((byte)'6');

	private final byte code;

	ListStatusType (byte code) {
		this.code  = code;
	}

	public byte getCode() { return code; }

	public static ListStatusType parse(String s) {
		switch(s) {
			case "1" : return ACK;
			case "2" : return RESPONSE;
			case "3" : return TIMED;
			case "4" : return EXECSTARTED;
			case "5" : return ALLDONE;
			case "6" : return ALERT;
		}
		return null;
	}

}