/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.f1x.api.message.fields;

// Generated by org.f1x.tools.DictionaryGenerator from QuickFIX dictionary
public enum ListOrderStatus implements org.f1x.api.message.types.ByteEnum {
	INBIDDINGPROCESS((byte)'1'),
	RECEIVEDFOREXECUTION((byte)'2'),
	EXECUTING((byte)'3'),
	CANCELING((byte)'4'),
	ALERT((byte)'5'),
	ALL_DONE((byte)'6'),
	REJECT((byte)'7');

	private final byte code;

	ListOrderStatus (byte code) {
		this.code  = code;
	}

	public byte getCode() { return code; }

	public static ListOrderStatus parse(String s) {
		switch(s) {
			case "1" : return INBIDDINGPROCESS;
			case "2" : return RECEIVEDFOREXECUTION;
			case "3" : return EXECUTING;
			case "4" : return CANCELING;
			case "5" : return ALERT;
			case "6" : return ALL_DONE;
			case "7" : return REJECT;
		}
		return null;
	}

}