/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.f1x.api.message.fields;

// Generated by org.f1x.tools.DictionaryGenerator from QuickFIX dictionary
public enum MassCancelRejectReason implements org.f1x.api.message.types.IntEnum {
	MASS_CANCEL_NOT_SUPPORTED(0),
	INVALID_OR_UNKNOWN_SECURITY(1),
	INVALID_OR_UNKNOWN_UNDERLYING(2),
	INVALID_OR_UNKNOWN_PRODUCT(3),
	INVALID_OR_UNKNOWN_CFICODE(4),
	INVALID_OR_UNKNOWN_SECURITY_TYPE(5),
	INVALID_OR_UNKNOWN_TRADING_SESSION(6),
	OTHER(99);

	private final int code;

	MassCancelRejectReason (int code) {
		this.code  = code;
	}

	public int getCode() { return code; }

	public static MassCancelRejectReason parse(String s) {
		switch(s) {
			case "0" : return MASS_CANCEL_NOT_SUPPORTED;
			case "1" : return INVALID_OR_UNKNOWN_SECURITY;
			case "2" : return INVALID_OR_UNKNOWN_UNDERLYING;
			case "3" : return INVALID_OR_UNKNOWN_PRODUCT;
			case "4" : return INVALID_OR_UNKNOWN_CFICODE;
			case "5" : return INVALID_OR_UNKNOWN_SECURITY_TYPE;
			case "6" : return INVALID_OR_UNKNOWN_TRADING_SESSION;
			case "99" : return OTHER;
		}
		return null;
	}

}