/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.f1x.api.message.fields;

// Generated by org.f1x.tools.DictionaryGenerator from QuickFIX dictionary
public enum MiscFeeType implements org.f1x.api.message.types.IntEnum {
	REGULATORY(1),
	TAX(2),
	LOCAL_COMMISSION(3),
	EXCHANGE_FEES(4),
	STAMP(5),
	LEVY(6),
	OTHER(7),
	MARKUP(8),
	CONSUMPTION_TAX(9),
	PER_TRANSACTION(10),
	CONVERSION(11),
	AGENT(12);

	private final int code;

	MiscFeeType (int code) {
		this.code  = code;
	}

	public int getCode() { return code; }

	public static MiscFeeType parse(String s) {
		switch(s) {
			case "1" : return REGULATORY;
			case "2" : return TAX;
			case "3" : return LOCAL_COMMISSION;
			case "4" : return EXCHANGE_FEES;
			case "5" : return STAMP;
			case "6" : return LEVY;
			case "7" : return OTHER;
			case "8" : return MARKUP;
			case "9" : return CONSUMPTION_TAX;
			case "10" : return PER_TRANSACTION;
			case "11" : return CONVERSION;
			case "12" : return AGENT;
		}
		return null;
	}

}