/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.f1x.api.message.fields;

// Generated by org.f1x.tools.DictionaryGenerator from QuickFIX dictionary
public enum NetworkRequestType implements org.f1x.api.message.types.ByteEnum {
	SNAPSHOT((byte)'1'),
	SUBSCRIBE((byte)'2'),
	STOP_SUBSCRIBING((byte)'4'),
	LEVEL_OF_DETAIL((byte)'8');

	private final byte code;

	NetworkRequestType (byte code) {
		this.code  = code;
	}

	public byte getCode() { return code; }

	public static NetworkRequestType parse(String s) {
		switch(s) {
			case "1" : return SNAPSHOT;
			case "2" : return SUBSCRIBE;
			case "4" : return STOP_SUBSCRIBING;
			case "8" : return LEVEL_OF_DETAIL;
		}
		return null;
	}

}