/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.f1x.api.message.fields;

// Generated by org.f1x.tools.DictionaryGenerator from QuickFIX dictionary
public enum OrderCapacity implements org.f1x.api.message.types.ByteEnum {
	AGENCY((byte)'A'),
	PROPRIETARY((byte)'G'),
	INDIVIDUAL((byte)'I'),
	PRINCIPAL((byte)'P'),
	RISKLESS_PRINCIPAL((byte)'R'),
	AGENT_FOR_OTHER_MEMBER((byte)'W');

	private final byte code;

	OrderCapacity (byte code) {
		this.code  = code;
	}

	public byte getCode() { return code; }

	public static OrderCapacity parse(String s) {
		switch(s) {
			case "A" : return AGENCY;
			case "G" : return PROPRIETARY;
			case "I" : return INDIVIDUAL;
			case "P" : return PRINCIPAL;
			case "R" : return RISKLESS_PRINCIPAL;
			case "W" : return AGENT_FOR_OTHER_MEMBER;
		}
		return null;
	}

}