/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.f1x.api.message.fields;

// Generated by org.f1x.tools.DictionaryGenerator from QuickFIX dictionary
public enum PosTransType implements org.f1x.api.message.types.ByteEnum {
	EXERCISE((byte)'1'),
	DO_NOT_EXERCISE((byte)'2'),
	POSITION_ADJUSTMENT((byte)'3'),
	POSITION_CHANGE_SUBMISSION_MARGIN_DISPOSITION((byte)'4'),
	PLEDGE((byte)'5');

	private final byte code;

	PosTransType (byte code) {
		this.code  = code;
	}

	public byte getCode() { return code; }

	public static PosTransType parse(String s) {
		switch(s) {
			case "1" : return EXERCISE;
			case "2" : return DO_NOT_EXERCISE;
			case "3" : return POSITION_ADJUSTMENT;
			case "4" : return POSITION_CHANGE_SUBMISSION_MARGIN_DISPOSITION;
			case "5" : return PLEDGE;
		}
		return null;
	}

}