/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.f1x.api.message.fields;

// Generated by org.f1x.tools.DictionaryGenerator from QuickFIX dictionary
public enum ProcessCode implements org.f1x.api.message.types.ByteEnum {
	REGULAR((byte)'0'),
	SOFT_DOLLAR((byte)'1'),
	STEP_IN((byte)'2'),
	STEP_OUT((byte)'3'),
	SOFT_DOLLAR_STEP_IN((byte)'4'),
	SOFT_DOLLAR_STEP_OUT((byte)'5'),
	PLAN_SPONSOR((byte)'6');

	private final byte code;

	ProcessCode (byte code) {
		this.code  = code;
	}

	public byte getCode() { return code; }

	public static ProcessCode parse(String s) {
		switch(s) {
			case "0" : return REGULAR;
			case "1" : return SOFT_DOLLAR;
			case "2" : return STEP_IN;
			case "3" : return STEP_OUT;
			case "4" : return SOFT_DOLLAR_STEP_IN;
			case "5" : return SOFT_DOLLAR_STEP_OUT;
			case "6" : return PLAN_SPONSOR;
		}
		return null;
	}

}