/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.f1x.api.message.fields;

// Generated by org.f1x.tools.DictionaryGenerator from QuickFIX dictionary
public enum Product implements org.f1x.api.message.types.IntEnum {
	AGENCY(1),
	COMMODITY(2),
	CORPORATE(3),
	CURRENCY(4),
	EQUITY(5),
	GOVERNMENT(6),
	INDEX(7),
	LOAN(8),
	MONEYMARKET(9),
	MORTGAGE(10),
	MUNICIPAL(11),
	OTHER(12),
	FINANCING(13);

	private final int code;

	Product (int code) {
		this.code  = code;
	}

	public int getCode() { return code; }

	public static Product parse(String s) {
		switch(s) {
			case "1" : return AGENCY;
			case "2" : return COMMODITY;
			case "3" : return CORPORATE;
			case "4" : return CURRENCY;
			case "5" : return EQUITY;
			case "6" : return GOVERNMENT;
			case "7" : return INDEX;
			case "8" : return LOAN;
			case "9" : return MONEYMARKET;
			case "10" : return MORTGAGE;
			case "11" : return MUNICIPAL;
			case "12" : return OTHER;
			case "13" : return FINANCING;
		}
		return null;
	}

}