/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.f1x.api.message.fields;

// Generated by org.f1x.tools.DictionaryGenerator from QuickFIX dictionary
public enum ProgRptReqs implements org.f1x.api.message.types.ByteEnum {
	BUYSIDE_EXPLICITLY_REQUESTS_STATUS_USING_STATUSREQUEST((byte)'1'),
	SELLSIDE_PERIODICALLY_SENDS_STATUS_USING_LISTSTATUS((byte)'2'),
	REAL_TIME_EXECUTION_REPORTS((byte)'3');

	private final byte code;

	ProgRptReqs (byte code) {
		this.code  = code;
	}

	public byte getCode() { return code; }

	public static ProgRptReqs parse(String s) {
		switch(s) {
			case "1" : return BUYSIDE_EXPLICITLY_REQUESTS_STATUS_USING_STATUSREQUEST;
			case "2" : return SELLSIDE_PERIODICALLY_SENDS_STATUS_USING_LISTSTATUS;
			case "3" : return REAL_TIME_EXECUTION_REPORTS;
		}
		return null;
	}

}