/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.f1x.api.message.fields;

// Generated by org.f1x.tools.DictionaryGenerator from QuickFIX dictionary
public enum QuantityType implements org.f1x.api.message.types.ByteEnum {
	SHARES((byte)'1'),
	BONDS((byte)'2'),
	CURRENTFACE((byte)'3'),
	ORIGINALFACE((byte)'4'),
	CURRENCY((byte)'5'),
	CONTRACTS((byte)'6'),
	OTHER((byte)'7'),
	PAR((byte)'8');

	private final byte code;

	QuantityType (byte code) {
		this.code  = code;
	}

	public byte getCode() { return code; }

	public static QuantityType parse(String s) {
		switch(s) {
			case "1" : return SHARES;
			case "2" : return BONDS;
			case "3" : return CURRENTFACE;
			case "4" : return ORIGINALFACE;
			case "5" : return CURRENCY;
			case "6" : return CONTRACTS;
			case "7" : return OTHER;
			case "8" : return PAR;
		}
		return null;
	}

}