/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.f1x.api.message.fields;

// Generated by org.f1x.tools.DictionaryGenerator from QuickFIX dictionary
public enum QuoteResponseLevel implements org.f1x.api.message.types.ByteEnum {
	NO_ACKNOWLEDGEMENT((byte)'0'),
	ACKNOWLEDGE_ONLY_NEGATIVE_OR_ERRONEOUS_QUOTES((byte)'1'),
	ACKNOWLEDGE_EACH_QUOTE_MESSAGES((byte)'2');

	private final byte code;

	QuoteResponseLevel (byte code) {
		this.code  = code;
	}

	public byte getCode() { return code; }

	public static QuoteResponseLevel parse(String s) {
		switch(s) {
			case "0" : return NO_ACKNOWLEDGEMENT;
			case "1" : return ACKNOWLEDGE_ONLY_NEGATIVE_OR_ERRONEOUS_QUOTES;
			case "2" : return ACKNOWLEDGE_EACH_QUOTE_MESSAGES;
		}
		return null;
	}

}