/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.f1x.api.message.fields;

// Generated by org.f1x.tools.DictionaryGenerator from QuickFIX dictionary
public enum QuoteCancelType implements org.f1x.api.message.types.ByteEnum {
	CANCEL_FOR_SYMBOL((byte)'1'),
	CANCEL_FOR_SECURITY_TYPE((byte)'2'),
	CANCEL_FOR_UNDERLYING_SYMBOL((byte)'3'),
	CANCEL_ALL_QUOTES((byte)'4');

	private final byte code;

	QuoteCancelType (byte code) {
		this.code  = code;
	}

	public byte getCode() { return code; }

	public static QuoteCancelType parse(String s) {
		switch(s) {
			case "1" : return CANCEL_FOR_SYMBOL;
			case "2" : return CANCEL_FOR_SECURITY_TYPE;
			case "3" : return CANCEL_FOR_UNDERLYING_SYMBOL;
			case "4" : return CANCEL_ALL_QUOTES;
		}
		return null;
	}

}