/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.f1x.api.message.fields;

// Generated by org.f1x.tools.DictionaryGenerator from QuickFIX dictionary
public enum SecurityRequestResult implements org.f1x.api.message.types.ByteEnum {
	VALID_REQUEST((byte)'0'),
	INVALID_OR_UNSUPPORTED_REQUEST((byte)'1'),
	NO_INSTRUMENTS_FOUND_THAT_MATCH_SELECTION_CRITERIA((byte)'2'),
	NOT_AUTHORIZED_TO_RETRIEVE_INSTRUMENT_DATA((byte)'3'),
	INSTRUMENT_DATA_TEMPORARILY_UNAVAILABLE((byte)'4'),
	REQUEST_FOR_INSTRUMENT_DATA_NOT_SUPPORTED((byte)'5');

	private final byte code;

	SecurityRequestResult (byte code) {
		this.code  = code;
	}

	public byte getCode() { return code; }

	public static SecurityRequestResult parse(String s) {
		switch(s) {
			case "0" : return VALID_REQUEST;
			case "1" : return INVALID_OR_UNSUPPORTED_REQUEST;
			case "2" : return NO_INSTRUMENTS_FOUND_THAT_MATCH_SELECTION_CRITERIA;
			case "3" : return NOT_AUTHORIZED_TO_RETRIEVE_INSTRUMENT_DATA;
			case "4" : return INSTRUMENT_DATA_TEMPORARILY_UNAVAILABLE;
			case "5" : return REQUEST_FOR_INSTRUMENT_DATA_NOT_SUPPORTED;
		}
		return null;
	}

}