/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.f1x.api.message.fields;

// Generated by org.f1x.tools.DictionaryGenerator from QuickFIX dictionary
public enum SecurityResponseType implements org.f1x.api.message.types.ByteEnum {
	ACCEPT_SECURITY_PROPOSAL_AS_IS((byte)'1'),
	ACCEPT_SECURITY_PROPOSAL_WITH_REVISIONS_AS_INDICATED_IN_THE_MESSAGE((byte)'2'),
	LIST_OF_SECURITY_TYPES_RETURNED_PER_REQUEST((byte)'3'),
	LIST_OF_SECURITIES_RETURNED_PER_REQUEST((byte)'4'),
	REJECT_SECURITY_PROPOSAL((byte)'5'),
	CAN_NOT_MATCH_SELECTION_CRITERIA((byte)'6');

	private final byte code;

	SecurityResponseType (byte code) {
		this.code  = code;
	}

	public byte getCode() { return code; }

	public static SecurityResponseType parse(String s) {
		switch(s) {
			case "1" : return ACCEPT_SECURITY_PROPOSAL_AS_IS;
			case "2" : return ACCEPT_SECURITY_PROPOSAL_WITH_REVISIONS_AS_INDICATED_IN_THE_MESSAGE;
			case "3" : return LIST_OF_SECURITY_TYPES_RETURNED_PER_REQUEST;
			case "4" : return LIST_OF_SECURITIES_RETURNED_PER_REQUEST;
			case "5" : return REJECT_SECURITY_PROPOSAL;
			case "6" : return CAN_NOT_MATCH_SELECTION_CRITERIA;
		}
		return null;
	}

}