/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.f1x.api.message.fields;

// Generated by org.f1x.tools.DictionaryGenerator from QuickFIX dictionary
public enum SecurityRequestType implements org.f1x.api.message.types.ByteEnum {
	REQUEST_SECURITY_IDENTITY_AND_SPECIFICATIONS((byte)'0'),
	REQUEST_SECURITY_IDENTITY_FOR_THE_SPECIFICATIONS_PROVIDED((byte)'1'),
	REQUEST_LIST_SECURITY_TYPES((byte)'2'),
	REQUEST_LIST_SECURITIES((byte)'3');

	private final byte code;

	SecurityRequestType (byte code) {
		this.code  = code;
	}

	public byte getCode() { return code; }

	public static SecurityRequestType parse(String s) {
		switch(s) {
			case "0" : return REQUEST_SECURITY_IDENTITY_AND_SPECIFICATIONS;
			case "1" : return REQUEST_SECURITY_IDENTITY_FOR_THE_SPECIFICATIONS_PROVIDED;
			case "2" : return REQUEST_LIST_SECURITY_TYPES;
			case "3" : return REQUEST_LIST_SECURITIES;
		}
		return null;
	}

}