/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.f1x.api.message.fields;

// Generated by org.f1x.tools.DictionaryGenerator from QuickFIX dictionary
public enum ShortSaleReason implements org.f1x.api.message.types.ByteEnum {
	DEALER_SOLD_SHORT((byte)'0'),
	DEALER_SOLD_SHORT_EXEMPT((byte)'1'),
	SELLING_CUSTOMER_SOLD_SHORT((byte)'2'),
	SELLING_CUSTOMER_SOLD_SHORT_EXEMPT((byte)'3'),
	QUALIFED_SERVICE_REPRESENTATIVE_OR_AUTOMATIC_GIVEUP_CONTRA_SIDE_SOLD_SHORT((byte)'4'),
	QSR_OR_AGU_CONTRA_SIDE_SOLD_SHORT_EXEMPT((byte)'5');

	private final byte code;

	ShortSaleReason (byte code) {
		this.code  = code;
	}

	public byte getCode() { return code; }

	public static ShortSaleReason parse(String s) {
		switch(s) {
			case "0" : return DEALER_SOLD_SHORT;
			case "1" : return DEALER_SOLD_SHORT_EXEMPT;
			case "2" : return SELLING_CUSTOMER_SOLD_SHORT;
			case "3" : return SELLING_CUSTOMER_SOLD_SHORT_EXEMPT;
			case "4" : return QUALIFED_SERVICE_REPRESENTATIVE_OR_AUTOMATIC_GIVEUP_CONTRA_SIDE_SOLD_SHORT;
			case "5" : return QSR_OR_AGU_CONTRA_SIDE_SOLD_SHORT_EXEMPT;
		}
		return null;
	}

}