/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.f1x.api.message.fields;

// Generated by org.f1x.tools.DictionaryGenerator from QuickFIX dictionary
public enum TerminationType implements org.f1x.api.message.types.ByteEnum {
	OVERNIGHT((byte)'1'),
	TERM((byte)'2'),
	FLEXIBLE((byte)'3'),
	OPEN((byte)'4');

	private final byte code;

	TerminationType (byte code) {
		this.code  = code;
	}

	public byte getCode() { return code; }

	public static TerminationType parse(String s) {
		switch(s) {
			case "1" : return OVERNIGHT;
			case "2" : return TERM;
			case "3" : return FLEXIBLE;
			case "4" : return OPEN;
		}
		return null;
	}

}