/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.f1x.api.message.fields;

// Generated by org.f1x.tools.DictionaryGenerator from QuickFIX dictionary
public enum TradSesStatus implements org.f1x.api.message.types.ByteEnum {
	UNKNOWN((byte)'0'),
	HALTED((byte)'1'),
	OPEN((byte)'2'),
	CLOSED((byte)'3'),
	PRE_OPEN((byte)'4'),
	PRE_CLOSE((byte)'5'),
	REQUEST_REJECTED((byte)'6');

	private final byte code;

	TradSesStatus (byte code) {
		this.code  = code;
	}

	public byte getCode() { return code; }

	public static TradSesStatus parse(String s) {
		switch(s) {
			case "0" : return UNKNOWN;
			case "1" : return HALTED;
			case "2" : return OPEN;
			case "3" : return CLOSED;
			case "4" : return PRE_OPEN;
			case "5" : return PRE_CLOSE;
			case "6" : return REQUEST_REJECTED;
		}
		return null;
	}

}