/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.f1x.api.message.fields;

// Generated by org.f1x.tools.DictionaryGenerator from QuickFIX dictionary
public enum TradeReportType implements org.f1x.api.message.types.ByteEnum {
	SUBMIT((byte)'0'),
	ALLEGED((byte)'1'),
	ACCEPT((byte)'2'),
	DECLINE((byte)'3'),
	ADDENDUM((byte)'4'),
	NO_WAS((byte)'5'),
	TRADE_REPORT_CANCEL((byte)'6'),
	LOCKED_IN_TRADE_BREAK((byte)'7');

	private final byte code;

	TradeReportType (byte code) {
		this.code  = code;
	}

	public byte getCode() { return code; }

	public static TradeReportType parse(String s) {
		switch(s) {
			case "0" : return SUBMIT;
			case "1" : return ALLEGED;
			case "2" : return ACCEPT;
			case "3" : return DECLINE;
			case "4" : return ADDENDUM;
			case "5" : return NO_WAS;
			case "6" : return TRADE_REPORT_CANCEL;
			case "7" : return LOCKED_IN_TRADE_BREAK;
		}
		return null;
	}

}