/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.f1x.api.message.fields;

// Generated by org.f1x.tools.DictionaryGenerator from QuickFIX dictionary
public enum TradeAllocIndicator implements org.f1x.api.message.types.ByteEnum {
	ALLOCATION_NOT_REQUIRED((byte)'0'),
	ALLOCATION_REQUIRED((byte)'1'),
	USE_ALLOCATION_PROVIDED_WITH_THE_TRADE((byte)'2');

	private final byte code;

	TradeAllocIndicator (byte code) {
		this.code  = code;
	}

	public byte getCode() { return code; }

	public static TradeAllocIndicator parse(String s) {
		switch(s) {
			case "0" : return ALLOCATION_NOT_REQUIRED;
			case "1" : return ALLOCATION_REQUIRED;
			case "2" : return USE_ALLOCATION_PROVIDED_WITH_THE_TRADE;
		}
		return null;
	}

}