/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.f1x.api.message.fields;

// Generated by org.f1x.tools.DictionaryGenerator from QuickFIX dictionary
public enum TradeReportRejectReason implements org.f1x.api.message.types.IntEnum {
	SUCCESSFUL(0),
	INVALID_PARTY_INFORMATION(1),
	UNKNOWN_INSTRUMENT(2),
	UNAUTHORIZED_TO_REPORT_TRADES(3),
	INVALID_TRADE_TYPE(4),
	OTHER(99);

	private final int code;

	TradeReportRejectReason (int code) {
		this.code  = code;
	}

	public int getCode() { return code; }

	public static TradeReportRejectReason parse(String s) {
		switch(s) {
			case "0" : return SUCCESSFUL;
			case "1" : return INVALID_PARTY_INFORMATION;
			case "2" : return UNKNOWN_INSTRUMENT;
			case "3" : return UNAUTHORIZED_TO_REPORT_TRADES;
			case "4" : return INVALID_TRADE_TYPE;
			case "99" : return OTHER;
		}
		return null;
	}

}