/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.f1x.api.message.fields;

// Generated by org.f1x.tools.DictionaryGenerator from QuickFIX dictionary
public enum UserStatus implements org.f1x.api.message.types.ByteEnum {
	LOGGED_IN((byte)'1'),
	NOT_LOGGED_IN((byte)'2'),
	USER_NOT_RECOGNISED((byte)'3'),
	PASSWORD_INCORRECT((byte)'4'),
	PASSWORD_CHANGED((byte)'5'),
	OTHER((byte)'6');

	private final byte code;

	UserStatus (byte code) {
		this.code  = code;
	}

	public byte getCode() { return code; }

	public static UserStatus parse(String s) {
		switch(s) {
			case "1" : return LOGGED_IN;
			case "2" : return NOT_LOGGED_IN;
			case "3" : return USER_NOT_RECOGNISED;
			case "4" : return PASSWORD_INCORRECT;
			case "5" : return PASSWORD_CHANGED;
			case "6" : return OTHER;
		}
		return null;
	}

}